// This maps error constants with error codes.
module.exports = {
  // User related error codes
  INVALID_API_KEY: -101,
  INVALID_TOKEN: -102,
  NO_TOKEN: -103,
  INVALID_USER: -104,
  INVALID_EMAIL_ADDRESS: -105,
  REGISTRATION_FIELDS_MISSING: -106,
  LOGIN_FAILED: -107,
  ERROR_IN_USER_ADDITION: -108,
  PASSWORD_DOES_NOT_MATCH: -109,
  CONFIRM_PASSWORD_NOT_SAME: -110,
  ERROR_IN_UPDATE_PASSWORD: -111,
  VERIFICATION_CODE_ERROR: -112,
  ERROR_WHILE_MAIL_SENDING: -113,
  TOKEN_EXPIRED: -114,
  PLEASE_TRY_AGAIN: -115,
  EMAIL_ALREADY_EXIST: -116,
  INVALID_APIKEY: -117,
  IMAGE_FILE_ERROR: -118,
  INVALID_PAGENO_OR_PAGESIZE: -119,
  CONFIRMATION_TOKEN_EXPIRED: -120,
  EMAIL_ID_NOT_REGISTER: -121,
  NO_USER_ROLE_FOUND_IN_DATABASE: -122,

  //Device Related error codes
  NOT_APP_USER: -123,

  ADDRESS_FETCH_ERROR: -124,

  NOTIFICATION_DATA_NOT_FOUND: -125,
  NOTIFICATION_NOT_FOUND: -126,
  DELETE_NOTIFICATION_ERROR: -127,
  NOT_ACTIVE_USER: -128,
  INVALID_BOOLEAN_VALUE: -129,
  EMPTY_STRING: -130,
  MISSING_INPUT: -131,
  INVALID_EMAIL_OR_PASSWORD_KEY: -132,
  PASSWORD_MISMATCH_ERROR: -133,
  INVALID_ID: -134,
  PDF_ERROR: -135,
  NOT_ADMIN_USER: -136,
  SUBSCRIPTION_ERROR: -137,
  USER_ID_REQUIRED: -138,
  IMAGE_URLS_MISSING: -139,
  REMOVE_IMAGES_ERROR: -140,
  FETCH_CHATS_COUNT_ERROR: -141,
  SUBSCRIPTION_NOT_FOUND: -142,
  CHATS_LIMIT_REACHED_ERROR: -143,
  SUBSCRIPTION_PLANS_NOT_FOUND: -144,
  INVALID_PLATFORM: -145,

  AUTHENTICATION_FAILED: 401,

  // Server related error codes
  NOT_FOUND: 404,
  UNKNOWN_ERROR: -520,
  VALIDATION_ERROR: -100,

  //Http error code.
  HTTP_SUCCESS: 200,
  HTTP_FAILED: 400,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
};
